#!/usr/bin/env bash
# validate-agent.sh — verify a generated project-agent subagent file.
# Adapted from anthropics/claude-code plugin-dev's validate-agent.sh,
# specialized for project agents produced by the bootstrap-project-agent skill.

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <path/to/agent.md>"
  echo ""
  echo "Validates project-agent subagent files generated by bootstrap-project-agent for:"
  echo "  - LF line endings"
  echo "  - YAML frontmatter (single-line plain description)"
  echo "  - Required fields: name, description"
  echo "  - Project agent defaults: isolation:worktree, memory:project"
  echo "  - Forbidden fields: tools, color, permissionMode, metadata, license"
  echo "  - Description: opens with 'Use when…' or 'Use proactively…'"
  echo "  - Description: ends with 'See \"When invoked\" in the agent body for worked scenarios.'"
  echo "  - Description: includes a negative trigger ('Do not …' / 'not for …')"
  echo "  - Body contains '## When invoked' and '## Return …' sections"
  echo "  - No absolute machine paths (Linux/macOS/Windows)"
  exit 1
fi

AGENT_FILE="$1"
errors=0
warnings=0

echo "Validating: $AGENT_FILE"
echo

if [ ! -f "$AGENT_FILE" ]; then
  echo "ERROR: file not found"
  exit 1
fi

# Pre-check: CRLF line endings will break every other check
if grep -q $'\r' "$AGENT_FILE"; then
  echo "ERROR: file has CRLF line endings; convert with 'dos2unix \"$AGENT_FILE\"' or 'tr -d \\\"\\\\r\\\" < in > out'"
  exit 1
fi

first_line="$(head -n 1 "$AGENT_FILE")"
if [ "$first_line" != "---" ]; then
  echo "ERROR: file must start with YAML frontmatter (---)"
  errors=$((errors+1))
fi

if ! awk 'NR>1 && /^---$/ {found=1; exit} END {exit !found}' "$AGENT_FILE"; then
  echo "ERROR: frontmatter not closed (missing second ---)"
  errors=$((errors+1))
fi

# Extract frontmatter and body
frontmatter="$(awk '/^---$/{i++; if(i==1) next; if(i==2) exit} i==1' "$AGENT_FILE")"
body="$(awk '/^---$/{i++; next} i>=2' "$AGENT_FILE")"

# --- Frontmatter parsing ---
# Try python3 + yaml first (handles block scalars, quoted strings, etc).
# Fall back to awk if python3 unavailable. Print KEY=VALUE pairs we care about.
if command -v python3 >/dev/null 2>&1; then
  parsed="$(python3 - "$AGENT_FILE" <<'PY' 2>/dev/null || true
import sys, re
try:
    import yaml
except ImportError:
    sys.exit(0)
path = sys.argv[1]
with open(path, "r", encoding="utf-8") as f:
    text = f.read()
m = re.search(r"^---\n(.*?)\n---\n", text, re.DOTALL)
if not m:
    sys.exit(0)
try:
    fm = yaml.safe_load(m.group(1)) or {}
except Exception:
    sys.exit(0)
def emit(k):
    v = fm.get(k)
    if v is None:
        return
    if isinstance(v, (dict, list)):
        # Just signal presence of complex types
        print(f"{k.upper()}_PRESENT=1")
    else:
        # Single-line value; replace any embedded newlines with literal \n marker
        s = str(v).replace("\n", "\\n")
        print(f"{k.upper()}={s}")
for k in ("name", "description", "model", "isolation", "memory", "tools",
         "color", "permissionMode", "metadata", "license"):
    emit(k)
# Detect block-scalar description: yaml normalizes it to a string but we can
# check the raw frontmatter for | or > on the description line
for line in m.group(1).splitlines():
    if re.match(r"^description:\s*[|>]", line):
        print("DESCRIPTION_BLOCK_SCALAR=1")
        break
PY
  )"
else
  parsed=""
fi

# Helper to get a value from python's output, with awk fallback
get_field() {
  local key="$1"
  local upper="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
  if [ -n "$parsed" ]; then
    printf '%s\n' "$parsed" | awk -F= -v k="$upper" '$1==k { sub(/^[A-Z_]+=/, ""); print; exit }'
  else
    # Awk fallback: only handles single-line plain scalars at column 1
    printf '%s\n' "$frontmatter" | awk -v k="$key" '
      $0 ~ "^" k ":" {
        sub("^" k ":[[:space:]]*", "");
        print;
        exit
      }'
  fi
}

field_present() {
  local key="$1"
  local upper="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
  if [ -n "$parsed" ]; then
    if printf '%s\n' "$parsed" | grep -qE "^(${upper}=|${upper}_PRESENT=)"; then
      return 0
    fi
    return 1
  else
    printf '%s\n' "$frontmatter" | awk -v k="$key" '$0 ~ "^" k ":" { found=1; exit } END { exit !found }'
  fi
}

# Detect block-scalar description (cannot be safely round-tripped here)
if printf '%s\n' "$parsed" | grep -q '^DESCRIPTION_BLOCK_SCALAR=1'; then
  echo "ERROR: description uses a YAML block scalar (| or >); rewrite as a single-line plain scalar"
  errors=$((errors+1))
fi

# --- name ---
name="$(get_field name)"
if [ -z "$name" ]; then
  echo "ERROR: missing required field: name"
  errors=$((errors+1))
else
  echo "OK    name: $name"
  if ! [[ "$name" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]]; then
    echo "ERROR: name must be lowercase alphanumeric + hyphens, no leading/trailing hyphen, no consecutive hyphens"
    errors=$((errors+1))
  fi
  if [ ${#name} -lt 1 ] || [ ${#name} -gt 64 ]; then
    echo "ERROR: name must be 1-64 characters (project agent template limit)"
    errors=$((errors+1))
  fi
  case "$name" in
    *-project) ;;
    *) echo "WARN  name should end in '-project' for the project agent convention"; warnings=$((warnings+1)) ;;
  esac
fi

# --- description ---
description="$(get_field description)"
if [ -z "$description" ]; then
  echo "ERROR: missing required field: description"
  errors=$((errors+1))
else
  desc_len=${#description}
  echo "OK    description: $desc_len characters"
  if [ "$desc_len" -lt 50 ]; then
    echo "ERROR: description too short for a project agent (want concrete trigger keywords)"
    errors=$((errors+1))
  fi
  if [ "$desc_len" -gt 1024 ]; then
    echo "ERROR: description exceeds 1024 characters (project agent template limit)"
    errors=$((errors+1))
  fi
  case "$description" in
    "Use this agent when"*|"Use proactively"*|"Use when"*)
      echo "OK    description opens with proper trigger pattern"
      ;;
    *)
      echo "ERROR: description must start with 'Use when…' or 'Use proactively…' (or 'Use this agent when…' for backwards compat)"
      errors=$((errors+1))
      ;;
  esac
  # Required tail phrase
  if [[ "$description" == *'See "When invoked" in the agent body for worked scenarios.' ]]; then
    echo "OK    description ends with the canonical pointer phrase"
  else
    echo "ERROR: description must end with: See \"When invoked\" in the agent body for worked scenarios."
    errors=$((errors+1))
  fi
  # Negative trigger heuristic
  if printf '%s\n' "$description" | grep -qiE "do not (invoke|use|call)|don't (invoke|use|call)|not for "; then
    echo "OK    description includes a negative trigger"
  else
    echo "ERROR: description should include a negative-trigger sentence (e.g. 'Do not invoke for…')"
    errors=$((errors+1))
  fi
fi

# --- isolation ---
isolation="$(get_field isolation)"
if [ "$isolation" != "worktree" ]; then
  echo "ERROR: project agents must set 'isolation: worktree' (got: '${isolation:-MISSING}')"
  errors=$((errors+1))
else
  echo "OK    isolation: worktree"
fi

# --- memory ---
memory="$(get_field memory)"
if [ "$memory" != "project" ]; then
  echo "ERROR: project agents must set 'memory: project' (got: '${memory:-MISSING}')"
  errors=$((errors+1))
else
  echo "OK    memory: project"
fi

# --- model (optional but if present must be valid) ---
model="$(get_field model)"
if [ -n "$model" ]; then
  case "$model" in
    inherit|sonnet|opus|haiku|claude-*) echo "OK    model: $model" ;;
    *) echo "WARN  unknown model: $model (expected inherit|sonnet|opus|haiku or full ID)"; warnings=$((warnings+1)) ;;
  esac
fi

# --- forbidden fields ---
for forbidden in tools color permissionMode metadata license; do
  if field_present "$forbidden"; then
    echo "ERROR: project agents must not set '$forbidden'. Remove from frontmatter."
    errors=$((errors+1))
  fi
done

echo

# --- Body checks ---
if [ -z "$body" ]; then
  echo "ERROR: empty body"
  errors=$((errors+1))
else
  body_len=${#body}
  echo "OK    body length: $body_len characters"
  if [ "$body_len" -lt 500 ]; then
    echo "ERROR: body too short ($body_len < 500). Project agents need substantive grounding."
    errors=$((errors+1))
  elif [ "$body_len" -gt 10000 ]; then
    echo "WARN  body very long ($body_len > 10000). Consider trimming."
    warnings=$((warnings+1))
  fi

  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+When[[:space:]]+invoked'; then
    echo "OK    body has 'When invoked' section"
  else
    echo "ERROR: body must include a '## When invoked' section"
    errors=$((errors+1))
  fi

  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+Return'; then
    echo "OK    body has 'Return' section"
  else
    echo "ERROR: body must include a '## Return …' section (handoff to orchestrator)"
    errors=$((errors+1))
  fi

  # Absolute machine paths: Linux, macOS, Windows
  abs_paths="$(printf '%s\n' "$body" | grep -oE '(/home/[^[:space:])`]+|/Users/[^[:space:])`]+|/root/[^[:space:])`]+|[A-Za-z]:\\[^[:space:])`]+)' | sort -u || true)"
  if [ -n "$abs_paths" ]; then
    echo "WARN  absolute machine paths found in body (use repo-relative):"
    while IFS= read -r p; do printf '      %s\n' "$p"; done <<< "$abs_paths"
    warnings=$((warnings+1))
  fi
fi

echo
echo "----------------------------------------"
if [ "$errors" -eq 0 ] && [ "$warnings" -eq 0 ]; then
  echo "PASS  all checks"
  exit 0
elif [ "$errors" -eq 0 ]; then
  echo "PASS  with $warnings warning(s)"
  exit 0
else
  echo "FAIL  $errors error(s), $warnings warning(s)"
  exit 1
fi
