#!/usr/bin/env bash
# validate-agent.sh — verify a generated SDE-style subagent file.
# Adapted from anthropics/claude-code plugin-dev's validate-agent.sh,
# specialized for SDE agents produced by the bootstrap-sde-agent skill.

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <path/to/agent.md>"
  echo ""
  echo "Validates SDE subagent files generated by bootstrap-sde-agent for:"
  echo "  - YAML frontmatter structure"
  echo "  - Required fields: name, description"
  echo "  - SDE defaults: isolation:worktree, memory:project"
  echo "  - Description starts with 'Use this agent when' or 'Use proactively'"
  echo "  - Body contains 'When invoked' and 'Return' sections"
  echo "  - No absolute machine paths"
  exit 1
fi

AGENT_FILE="$1"
errors=0
warnings=0

echo "Validating: $AGENT_FILE"
echo

if [ ! -f "$AGENT_FILE" ]; then
  echo "ERROR: file not found"
  exit 1
fi

first_line="$(head -n 1 "$AGENT_FILE")"
if [ "$first_line" != "---" ]; then
  echo "ERROR: file must start with YAML frontmatter (---)"
  errors=$((errors+1))
fi

if ! awk 'NR>1 && /^---$/ {found=1; exit} END {exit !found}' "$AGENT_FILE"; then
  echo "ERROR: frontmatter not closed (missing second ---)"
  errors=$((errors+1))
fi

frontmatter="$(awk '/^---$/{i++; if(i==1) next; if(i==2) exit} i==1' "$AGENT_FILE")"
body="$(awk '/^---$/{i++; next} i>=2' "$AGENT_FILE")"

# name
name="$(printf '%s\n' "$frontmatter" | awk -F': *' '$1=="name"{print $2; exit}')"
if [ -z "$name" ]; then
  echo "ERROR: missing required field: name"
  errors=$((errors+1))
else
  echo "OK    name: $name"
  if ! [[ "$name" =~ ^[a-z0-9][a-z0-9-]*[a-z0-9]$ ]]; then
    echo "ERROR: name must be lowercase alphanumeric + hyphens, no leading/trailing hyphen"
    errors=$((errors+1))
  fi
  if [ ${#name} -lt 3 ] || [ ${#name} -gt 64 ]; then
    echo "ERROR: name must be 3-64 characters"
    errors=$((errors+1))
  fi
  case "$name" in
    *-sde) ;;
    *) echo "WARN  name should end in '-sde' for the SDE convention"; warnings=$((warnings+1)) ;;
  esac
fi

# description (single-line block scalar; no folded multiline support here)
description="$(printf '%s\n' "$frontmatter" | awk -F': *' '$1=="description"{
  sub(/^description: */, "");
  print; exit
}' | sed 's/^description: *//')"
if [ -z "$description" ]; then
  # Fallback for descriptions that wrap
  description="$(printf '%s\n' "$frontmatter" | sed -n '/^description:/,/^[a-z_-]*:/p' | sed 's/^description: *//' | head -c 2000)"
fi
if [ -z "$description" ]; then
  echo "ERROR: missing required field: description"
  errors=$((errors+1))
else
  desc_len=${#description}
  echo "OK    description: $desc_len characters"
  if [ "$desc_len" -lt 50 ]; then
    echo "ERROR: description too short for SDE agent (want concrete trigger keywords)"
    errors=$((errors+1))
  fi
  if [ "$desc_len" -gt 1024 ]; then
    echo "ERROR: description exceeds agentskills.io max of 1024 characters"
    errors=$((errors+1))
  fi
  # leading-token check
  case "$description" in
    Use\ this\ agent\ when*|Use\ proactively*|Use\ when*)
      echo "OK    description opens with proper trigger pattern"
      ;;
    *)
      echo "ERROR: description must start with 'Use this agent when…' or 'Use proactively…' or 'Use when…'"
      errors=$((errors+1))
      ;;
  esac
fi

# isolation
isolation="$(printf '%s\n' "$frontmatter" | awk -F': *' '$1=="isolation"{print $2; exit}')"
if [ "$isolation" != "worktree" ]; then
  echo "ERROR: SDE agents must set 'isolation: worktree' (got: '${isolation:-MISSING}')"
  errors=$((errors+1))
else
  echo "OK    isolation: worktree"
fi

# memory
memory="$(printf '%s\n' "$frontmatter" | awk -F': *' '$1=="memory"{print $2; exit}')"
if [ "$memory" != "project" ]; then
  echo "ERROR: SDE agents must set 'memory: project' (got: '${memory:-MISSING}')"
  errors=$((errors+1))
else
  echo "OK    memory: project"
fi

# model (optional but if present must be valid)
model="$(printf '%s\n' "$frontmatter" | awk -F': *' '$1=="model"{print $2; exit}')"
if [ -n "$model" ]; then
  case "$model" in
    inherit|sonnet|opus|haiku|claude-*) echo "OK    model: $model" ;;
    *) echo "WARN  unknown model: $model (expected inherit|sonnet|opus|haiku or full ID)"; warnings=$((warnings+1)) ;;
  esac
fi

# tools should NOT be set on an SDE agent
if printf '%s\n' "$frontmatter" | grep -q '^tools:'; then
  echo "WARN  'tools' field is set; SDE agents should inherit. Restrict via settings.json instead."
  warnings=$((warnings+1))
fi

echo

# Body checks
if [ -z "$body" ]; then
  echo "ERROR: empty body"
  errors=$((errors+1))
else
  body_len=${#body}
  echo "OK    body length: $body_len characters"
  if [ "$body_len" -lt 500 ]; then
    echo "ERROR: body too short ($body_len < 500). SDE agents need substantive grounding."
    errors=$((errors+1))
  elif [ "$body_len" -gt 10000 ]; then
    echo "WARN  body very long ($body_len > 10000). Consider trimming."
    warnings=$((warnings+1))
  fi

  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+When invoked'; then
    echo "OK    body has 'When invoked' section"
  else
    echo "ERROR: body must include a '## When invoked' section"
    errors=$((errors+1))
  fi

  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+Return'; then
    echo "OK    body has 'Return' section"
  else
    echo "ERROR: body must include a '## Return …' section (handoff to orchestrator)"
    errors=$((errors+1))
  fi

  # absolute machine paths
  abs_paths="$(printf '%s\n' "$body" | grep -oE '(/home/[^[:space:])]+|/Users/[^[:space:])]+|C:\\\\[^[:space:])]+)' | sort -u || true)"
  if [ -n "$abs_paths" ]; then
    echo "WARN  absolute machine paths found in body (use repo-relative):"
    printf '      %s\n' $abs_paths
    warnings=$((warnings+1))
  fi
fi

echo
echo "----------------------------------------"
if [ "$errors" -eq 0 ] && [ "$warnings" -eq 0 ]; then
  echo "PASS  all checks"
  exit 0
elif [ "$errors" -eq 0 ]; then
  echo "PASS  with $warnings warning(s)"
  exit 0
else
  echo "FAIL  $errors error(s), $warnings warning(s)"
  exit 1
fi
