#!/usr/bin/env bash
# validate-orchestrator.sh — verify a generated orchestrator subagent file.
# Sibling of bootstrap-project-agent's validate-agent.sh; specialized for
# orchestrators (main-session-agent style, not delegated-subagent style).

set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <path/to/orchestrator.md>"
  echo ""
  echo "Validates orchestrator files generated by bootstrap-orchestrator-agent for:"
  echo "  - LF line endings"
  echo "  - YAML frontmatter (single-line plain description)"
  echo "  - Required fields: name, description, tools"
  echo "  - tools must include Agent(<at-least-one-named-agent>)"
  echo "  - tools must NOT include Edit, Write, MultiEdit, NotebookEdit"
  echo "  - Forbidden frontmatter fields: isolation, color, permissionMode, metadata, license"
  echo "  - Description: opens with 'Use when…' or 'Use proactively…' / 'Use as the main session agent when…'"
  echo "  - Description: ends with the canonical pointer phrase"
  echo "  - Description: includes a negative trigger"
  echo "  - Body contains '## When invoked', '## Dispatch protocol', '## Return …' sections"
  echo "  - No absolute machine paths beyond registry-derived repo paths (warn)"
  exit 1
fi

ORCH_FILE="$1"
errors=0
warnings=0

echo "Validating: $ORCH_FILE"
echo

if [ ! -f "$ORCH_FILE" ]; then
  echo "ERROR: file not found"
  exit 1
fi

# Pre-check: CRLF line endings
if grep -q $'\r' "$ORCH_FILE"; then
  echo "ERROR: file has CRLF line endings; convert with 'dos2unix \"$ORCH_FILE\"'"
  exit 1
fi

first_line="$(head -n 1 "$ORCH_FILE")"
if [ "$first_line" != "---" ]; then
  echo "ERROR: file must start with YAML frontmatter (---)"
  errors=$((errors+1))
fi

if ! awk 'NR>1 && /^---$/ {found=1; exit} END {exit !found}' "$ORCH_FILE"; then
  echo "ERROR: frontmatter not closed (missing second ---)"
  errors=$((errors+1))
fi

frontmatter="$(awk '/^---$/{i++; if(i==1) next; if(i==2) exit} i==1' "$ORCH_FILE")"
body="$(awk '/^---$/{i++; next} i>=2' "$ORCH_FILE")"

# --- Frontmatter parsing via python3 + yaml ---
if command -v python3 >/dev/null 2>&1; then
  parsed="$(python3 - "$ORCH_FILE" <<'PY' 2>/dev/null || true
import sys, re
try:
    import yaml
except ImportError:
    sys.exit(0)
path = sys.argv[1]
with open(path, "r", encoding="utf-8") as f:
    text = f.read()
m = re.search(r"^---\n(.*?)\n---\n", text, re.DOTALL)
if not m:
    sys.exit(0)
try:
    fm = yaml.safe_load(m.group(1)) or {}
except Exception:
    sys.exit(0)
def emit(k):
    v = fm.get(k)
    if v is None:
        return
    if isinstance(v, (dict, list)):
        print(f"{k.upper()}_PRESENT=1")
    else:
        s = str(v).replace("\n", "\\n")
        print(f"{k.upper()}={s}")
for k in ("name", "description", "model", "tools", "isolation", "memory",
         "color", "permissionMode", "metadata", "license", "disallowedTools",
         "background", "effort"):
    emit(k)
for line in m.group(1).splitlines():
    if re.match(r"^description:\s*[|>]", line):
        print("DESCRIPTION_BLOCK_SCALAR=1")
        break
PY
  )"
else
  parsed=""
fi

get_field() {
  local key="$1"
  local upper="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
  if [ -n "$parsed" ]; then
    printf '%s\n' "$parsed" | awk -F= -v k="$upper" '$1==k { sub(/^[A-Z_]+=/, ""); print; exit }'
  else
    printf '%s\n' "$frontmatter" | awk -v k="$key" '
      $0 ~ "^" k ":" { sub("^" k ":[[:space:]]*", ""); print; exit
      }'
  fi
}

field_present() {
  local key="$1"
  local upper="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
  if [ -n "$parsed" ]; then
    if printf '%s\n' "$parsed" | grep -qE "^(${upper}=|${upper}_PRESENT=)"; then
      return 0
    fi
    return 1
  else
    printf '%s\n' "$frontmatter" | awk -v k="$key" '$0 ~ "^" k ":" { found=1; exit } END { exit !found }'
  fi
}

if printf '%s\n' "$parsed" | grep -q '^DESCRIPTION_BLOCK_SCALAR=1'; then
  echo "ERROR: description uses a YAML block scalar (| or >); rewrite as a single-line plain scalar"
  errors=$((errors+1))
fi

# --- name ---
name="$(get_field name)"
if [ -z "$name" ]; then
  echo "ERROR: missing required field: name"
  errors=$((errors+1))
else
  echo "OK    name: $name"
  if ! [[ "$name" =~ ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$ ]]; then
    echo "ERROR: name must be lowercase alphanumeric + hyphens, no leading/trailing hyphen, no consecutive hyphens"
    errors=$((errors+1))
  fi
  if [ ${#name} -lt 1 ] || [ ${#name} -gt 64 ]; then
    echo "ERROR: name must be 1-64 characters"
    errors=$((errors+1))
  fi
fi

# --- description ---
description="$(get_field description)"
if [ -z "$description" ]; then
  echo "ERROR: missing required field: description"
  errors=$((errors+1))
else
  desc_len=${#description}
  echo "OK    description: $desc_len characters"
  if [ "$desc_len" -lt 50 ]; then
    echo "ERROR: description too short (want concrete trigger keywords + negative trigger)"
    errors=$((errors+1))
  fi
  if [ "$desc_len" -gt 1024 ]; then
    echo "ERROR: description exceeds 1024 characters"
    errors=$((errors+1))
  fi
  case "$description" in
    "Use this agent when"*|"Use proactively"*|"Use when"*|"Use as the main session agent when"*)
      echo "OK    description opens with proper trigger pattern"
      ;;
    *)
      echo "ERROR: description must start with 'Use when…' / 'Use proactively…' / 'Use as the main session agent when…'"
      errors=$((errors+1))
      ;;
  esac
  if [[ "$description" == *'See "When invoked" in the agent body for worked scenarios.' ]]; then
    echo "OK    description ends with the canonical pointer phrase"
  else
    echo "ERROR: description must end with: See \"When invoked\" in the agent body for worked scenarios."
    errors=$((errors+1))
  fi
  if printf '%s\n' "$description" | grep -qiE "do not (use|invoke|call)|don't (use|invoke|call)|not for "; then
    echo "OK    description includes a negative trigger"
  else
    echo "ERROR: description should include a negative-trigger sentence"
    errors=$((errors+1))
  fi
fi

# --- tools (REQUIRED for orchestrator) ---
tools="$(get_field tools)"
if [ -z "$tools" ]; then
  echo "ERROR: missing required field: tools (orchestrators must restrict the Agent allowlist)"
  errors=$((errors+1))
else
  echo "OK    tools: $tools"
  # Must include Agent(...) with at least one named agent
  if printf '%s\n' "$tools" | grep -qE 'Agent\([^)]*[a-z][^)]*\)'; then
    echo "OK    tools includes Agent(<named-specialists>)"
    # Cross-check: at least one allowlist name (or its project-name root) should appear in the description.
    # Descriptions read in human terms ("parallax", "streamr"), not file-suffixed ones ("parallax-agent"),
    # so we strip common agent suffixes before substring-matching.
    if [ -n "$description" ]; then
      allowlist_names="$(printf '%s\n' "$tools" | grep -oE 'Agent\([^)]+\)' | head -1 | sed -E 's/^Agent\(//; s/\)$//; s/[[:space:]]*,[[:space:]]*/\n/g' | grep -v '^$' || true)"
      mention_count=0
      while IFS= read -r agent_name; do
        [ -z "$agent_name" ] && continue
        # Strip trailing -agent, -sde, -project suffixes for the substring search
        root="$(printf '%s' "$agent_name" | sed -E 's/-(agent|sde|project)$//')"
        # Match either the full name or the suffix-stripped root
        if printf '%s\n' "$description" | grep -qiE "(^|[^a-zA-Z0-9])($(printf '%s' "$agent_name" | sed 's/[][\.*^$/]/\\&/g')|$(printf '%s' "$root" | sed 's/[][\.*^$/]/\\&/g'))([^a-zA-Z0-9]|$)"; then
          mention_count=$((mention_count+1))
        fi
      done <<< "$allowlist_names"
      total_agents="$(printf '%s\n' "$allowlist_names" | grep -c '^.' || true)"
      if [ "$mention_count" -ge 1 ]; then
        echo "OK    description mentions $mention_count of $total_agents registered specialist(s) (by name or project root)"
      else
        echo "ERROR: description does not mention any agent from the Agent(...) allowlist (or their project-name roots) — orchestrator routing relies on description naming the registered fleet"
        errors=$((errors+1))
      fi
    fi
  else
    echo "ERROR: tools must include Agent(<at-least-one-named-agent>) — bare 'Agent' lets the orchestrator spawn anything; restrict to your registered fleet"
    errors=$((errors+1))
  fi
  # Must NOT include edit-style tools
  for forbidden_tool in Edit Write MultiEdit NotebookEdit; do
    if printf '%s\n' "$tools" | grep -qwE "$forbidden_tool"; then
      echo "ERROR: tools must not include '$forbidden_tool' — orchestrators dispatch; specialists edit"
      errors=$((errors+1))
    fi
  done
fi

# --- model ---
model="$(get_field model)"
if [ -n "$model" ]; then
  case "$model" in
    inherit|sonnet|opus|haiku|claude-*) echo "OK    model: $model" ;;
    *) echo "WARN  unknown model: $model"; warnings=$((warnings+1)) ;;
  esac
fi

# --- isolation MUST NOT be present ---
if field_present isolation; then
  isolation_value="$(get_field isolation)"
  echo "ERROR: orchestrators must not set 'isolation' (got: '$isolation_value'). The orchestrator IS the operator's session — there is no work tree to isolate. Remove the field."
  errors=$((errors+1))
fi

# --- memory: omit OR user (project doesn't fit cross-repo) ---
memory="$(get_field memory)"
if [ -n "$memory" ]; then
  case "$memory" in
    user) echo "OK    memory: user (cross-project orchestration learnings)" ;;
    project) echo "WARN  memory: project — project memory is per-repo; orchestrators span repos. Prefer 'user' or omit." ; warnings=$((warnings+1)) ;;
    local) echo "OK    memory: local (gitignored)" ;;
    *) echo "WARN  unknown memory scope: $memory" ; warnings=$((warnings+1)) ;;
  esac
fi

# --- forbidden top-level fields ---
for forbidden in color permissionMode metadata license disallowedTools background effort; do
  if field_present "$forbidden"; then
    echo "ERROR: orchestrators must not set '$forbidden'. Remove from frontmatter."
    errors=$((errors+1))
  fi
done

echo

# --- Body checks ---
if [ -z "$body" ]; then
  echo "ERROR: empty body"
  errors=$((errors+1))
else
  body_len=${#body}
  echo "OK    body length: $body_len characters"
  if [ "$body_len" -lt 1500 ]; then
    echo "ERROR: body too short ($body_len < 1500). Orchestrators need substantive coordination guidance."
    errors=$((errors+1))
  elif [ "$body_len" -gt 15000 ]; then
    echo "WARN  body very long ($body_len > 15000). Consider trimming."
    warnings=$((warnings+1))
  fi

  # Required body sections
  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+When[[:space:]]+invoked'; then
    echo "OK    body has '## When invoked' section"
  else
    echo "ERROR: body must include a '## When invoked' section"
    errors=$((errors+1))
  fi

  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+(Dispatch[[:space:]]+protocol|How[[:space:]]+to[[:space:]]+dispatch)'; then
    echo "OK    body has '## Dispatch protocol' section"
  else
    echo "ERROR: body must include a '## Dispatch protocol' section (the per-call briefing template)"
    errors=$((errors+1))
  fi

  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+Return'; then
    echo "OK    body has '## Return …' section"
  else
    echo "ERROR: body must include a '## Return …' section (rollup format to the operator)"
    errors=$((errors+1))
  fi

  if printf '%s\n' "$body" | grep -qiE '^##[[:space:]]+(The[[:space:]]+specialists|Specialists|Available[[:space:]]+specialists|Registered[[:space:]]+agents)'; then
    echo "OK    body has '## The specialists' section"
  else
    echo "ERROR: body must include a '## The specialists' (or equivalent) section listing the registered fleet"
    errors=$((errors+1))
  fi

  # Anti-pattern: must NOT call orchestrator a "manager" or specialists "reports"
  if printf '%s\n' "$body" | grep -qiE '\bmanager\b|\bsubordinate\b|\bdirect[[:space:]]+report\b'; then
    echo "WARN  body uses 'manager'/'subordinate'/'direct report' language — orchestrators dispatch focused work to peers, not supervise reports. Reword."
    warnings=$((warnings+1))
  fi
fi

echo
echo "----------------------------------------"
if [ "$errors" -eq 0 ] && [ "$warnings" -eq 0 ]; then
  echo "PASS  all checks"
  exit 0
elif [ "$errors" -eq 0 ]; then
  echo "PASS  with $warnings warning(s)"
  exit 0
else
  echo "FAIL  $errors error(s), $warnings warning(s)"
  exit 1
fi
